Repository recast-hep/recast-atlas, pull requests merged in 2021-10, with the labels that each got.

#53 fix: strip path
  src/recastatlas/backends/reana.py
Labels: fix

#52 build: Require setuptools<58.0.0 for reana extra
  setup.py
Labels: build

#56 build: Revise MANIFEST.in strategy to properly use prune
  MANIFEST.in
Labels: build

#57 ci: Add workflow to deploy to distributions to TestPyPI and PyPI
  .github/workflows/deploy.yml
  .github/workflows/publish-package.yml
Labels: ci

#58 Update README.md
  README.md
Labels: docs

#60 ci: Publish Docker images on merges and releases
  .github/workflows/deploy.yml
  .github/workflows/docker.yml
  deploy/deploy.sh
Labels: ci, docker

#61 docs: Add release instructions for maintainers
  docs/maintainer-notes.md
Labels: docs

#66 ci: Add Kubernetes and REANA dependencies to CI
  .github/workflows/ci.yml
Labels: ci
